services:
  - type: web
    name: management-system
    env: python
    buildCommand: pip install -r requirements.txt && python setup_dev.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        generateValue: true
      - key: SECRET_KEY
        generateValue: true